name: Deploy Next.js website to Cloudflare

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  start-server:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Start development server
      run: npm run dev &

    - name: Wait for development server to start
      run: |
        timeout=0
        until curl --verbose --fail http://localhost:3000 || [ $timeout -eq 60 ]; do
          echo "Waiting for development server to start..."
          sleep 2
          timeout=$((timeout + 2))
        done
        if [ $timeout -eq 60 ]; then
          echo "Development server failed to start" >&2
          exit 1
        fi

  build-and-export:
    runs-on: ubuntu-latest
    needs: start-server
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build and export Next.js website
      run: npm run build && npm run export

    - name: Export website to PDF
      uses: chrispat/pdfcrowd-action@v1.0.0
      with:
        api_key: ${{ secrets.PDFCROWD_API_KEY }}
        source: http://localhost:3000
        destination: ./out/atif-mohammed-cv.pdf

    - name: Copy PDF to public directory
      run: cp ./out/atif-mohammed-cv.pdf ./public

  debug:
    runs-on: ubuntu-latest
    needs: build-and-export
    steps:
    - name: List files in the output directory
      run: ls -R ./out

  deploy-to-cloudflare:
    runs-on: ubuntu-latest
    needs: debug
    steps:
    - name: Upload to Cloudflare
      uses: cloudflare/cloudflare-deploy@v1.5.0
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        siteId: <your-site-id>
        dir: ./out
        uploadConcurrency: 20
        purgeEverything: true
