name: GitHub Pages CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'

jobs:
  build_and_release:
    runs-on: ubuntu-20.04
    steps:
    - name: Dev Server
      run: |
        npm install
        npm build
        rm -rf ./docs
        yarn next export -o "./docs/"
        yarn dev &
        sleep 10 &&
        node .\scripts\makepdf.js