name: GitHub Pages CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'

jobs:
  build_and_release:
    runs-on: ubuntu-20.04
    steps:
    - name: Build the site
      run: |
        yarn install
